### PR TITLE
Venmo Fix GraphQL Typo

### LINKED ISSUE #749: Venmo - Validation error of type FieldUndefined: Field 'userNameshippingAddress
### Braintree SDK Version

4.32.0

### Environment

Sandbox

### Android Version & Device

Samsung A13 - Android 13

### Braintree dependencies

  com.braintreepayments.api:venmo:4.32.0

### Describe the bug

When using version `4.32.0` of the Venmo Client. After calling `tokenizeVenmoAccount` I get an `UnexpectedException` in the `onVenmoFailure` callback.

The message of the error is:
`Validation error of type FieldUndefined: Field 'userNameshippingAddress' in type 'VenmoPayerInfo' is undefined @ 'node/payerInfo/userNameshippingAddress'`.

Looks like the exception is happening when calling the following GraphQL query:
```
{
    "query": "query PaymentContext($id: ID!) { node(id: $id) { ... on VenmoPaymentContext { paymentMethodId userName payerInfo { firstName lastName phoneNumber email externalId userNameshippingAddress { fullName addressLine1 addressLine2 adminArea1 adminArea2 postalCode countryCode } billingAddress { fullName addressLine1 addressLine2 adminArea1 adminArea2 postalCode countryCode } } } } }",
    "variables": {
        "id": "xxxxxx"
        }
    }
}
```

This doesn't happen when using versions `4.31.0` or earlier.

### To reproduce

``` kotlin
val request = VenmoRequest(VenmoPaymentMethodUsage.MULTI_USE).apply {
    profileId = "abcxyz"
    shouldVault = true
}
venmoClient.tokenizeVenmoAccount(this, request)
```

### Expected behavior

Get a valid nonce token.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by sshropshire**
### Summary of changes

* Venmo
  * Add missing space to Venmo `PaymentContext` GraphQL query (fixes #749)

 ### Checklist

 - [x] Added a changelog entry

- @sshropshire

### CODE REVIEW

**Review by jaxdesmarais — APPROVED** [review]

File: Venmo/src/main/java/com/braintreepayments/api/VenmoApi.java [hunk 1]
```diff
@@ -84,7 +84,7 @@ public void onResult(String responseBody, Exception httpError) {
     void createNonceFromPaymentContext(String paymentContextId, final VenmoOnActivityResultCallback callback) {
         JSONObject params = new JSONObject();
         try {
-            params.put("query", "query PaymentContext($id: ID!) { node(id: $id) { ... on VenmoPaymentContext { paymentMethodId userName payerInfo { firstName lastName phoneNumber email externalId userName" +
+            params.put("query", "query PaymentContext($id: ID!) { node(id: $id) { ... on VenmoPaymentContext { paymentMethodId userName payerInfo { firstName lastName phoneNumber email externalId userName " +
```
Comment (scannillo) [inline Venmo/src/main/java/com/braintreepayments/api/VenmoApi.java:87]: Take it or leave it - maybe just one-line this whole string to avoid any string concat issues in the future

Comment (sshropshire) [reply Venmo/src/main/java/com/braintreepayments/api/VenmoApi.java:87]: Yeah I agree. Ideally we move this into a raw resource [like on PPCP](https://github.com/paypal/Android-SDK/blob/a9633573119f7580a08f3826b3fdff4363f467ce/CorePayments/src/main/res/raw/graphql_query_funding_eligibility.graphql).
